# Generated by Django 5.2.14 on 2026-05-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_create_default_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="amount_minor",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_minor",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance_minor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
